### ISSUE TITLE
TypeError during traversal

### ISSUE THREAD

**Issue by Elberet** [jsdoctypeparser/jsdoctypeparser#103]
I'm encountering a `TypeError` in `jsdoctypeparser` while linting some javascript source file via `eslint` and `eslint-plugin-jsdoc`:

```
[Error - 10:36:57] TypeError: Cannot convert undefined or null to object
Occurred while linting C:\...\src\lib\FooFactory.js:1
    at Function.keys (<anonymous>)
    at _collectChildNodeInfo (C:\...\node_modules\jsdoctypeparser\lib\traversing.js:139:10)
    at traverse (C:\...\node_modules\jsdoctypeparser\lib\traversing.js:17:27)
    at C:\...\node_modules\jsdoctypeparser\lib\traversing.js:19:7
    at Array.forEach (<anonymous>)
    at traverse (C:\...\node_modules\jsdoctypeparser\lib\traversing.js:18:19)
    at C:\...\node_modules\eslint-plugin-jsdoc\dist\rules\checkTypes.js:130:35
    at Array.forEach (<anonymous>)
    at _default.iterateAllJsdocs (C:\...\node_modules\eslint-plugin-jsdoc\dist\rules\checkTypes.js:44:29)
    at C:\...\node_modules\eslint-plugin-jsdoc\dist\iterateJsdoc.js:444:13
```

See gajus/eslint-plugin-jsdoc#145 for additional background.

Unfortunately, I cannot publish the actual source file.

**Comment by brettz9** [comment]
Could you do some logging of `node` right before line 139 of `lib\traversing`?

**Comment by brettz9** [comment]
And/or provide some sample code which triggers this traversal error? I could not replicate with the code on https://github.com/gajus/eslint-plugin-jsdoc/issues/145

**Comment by Elberet** [comment]
I have prepared a repro here: https://github.com/Elberet/eslint-jsdoc-typeof-repro
Under Win 10 x64 with Node.js 12.13.1, running `eslint .` results in a dump identical to the one posted above.
